-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fast_accel_fast_accel_Pipeline_VITIS_LOOP_14_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    img_in : IN STD_LOGIC_VECTOR (63 downto 0);
    IMG_V_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_0_ce0 : OUT STD_LOGIC;
    IMG_V_0_we0 : OUT STD_LOGIC;
    IMG_V_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_1_ce0 : OUT STD_LOGIC;
    IMG_V_1_we0 : OUT STD_LOGIC;
    IMG_V_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_2_ce0 : OUT STD_LOGIC;
    IMG_V_2_we0 : OUT STD_LOGIC;
    IMG_V_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_3_ce0 : OUT STD_LOGIC;
    IMG_V_3_we0 : OUT STD_LOGIC;
    IMG_V_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_4_ce0 : OUT STD_LOGIC;
    IMG_V_4_we0 : OUT STD_LOGIC;
    IMG_V_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_5_ce0 : OUT STD_LOGIC;
    IMG_V_5_we0 : OUT STD_LOGIC;
    IMG_V_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_6_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_6_ce0 : OUT STD_LOGIC;
    IMG_V_6_we0 : OUT STD_LOGIC;
    IMG_V_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_7_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_7_ce0 : OUT STD_LOGIC;
    IMG_V_7_we0 : OUT STD_LOGIC;
    IMG_V_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_8_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_8_ce0 : OUT STD_LOGIC;
    IMG_V_8_we0 : OUT STD_LOGIC;
    IMG_V_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_9_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_9_ce0 : OUT STD_LOGIC;
    IMG_V_9_we0 : OUT STD_LOGIC;
    IMG_V_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_10_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_10_ce0 : OUT STD_LOGIC;
    IMG_V_10_we0 : OUT STD_LOGIC;
    IMG_V_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_11_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_11_ce0 : OUT STD_LOGIC;
    IMG_V_11_we0 : OUT STD_LOGIC;
    IMG_V_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_12_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_12_ce0 : OUT STD_LOGIC;
    IMG_V_12_we0 : OUT STD_LOGIC;
    IMG_V_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_13_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_13_ce0 : OUT STD_LOGIC;
    IMG_V_13_we0 : OUT STD_LOGIC;
    IMG_V_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_14_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_14_ce0 : OUT STD_LOGIC;
    IMG_V_14_we0 : OUT STD_LOGIC;
    IMG_V_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_15_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_15_ce0 : OUT STD_LOGIC;
    IMG_V_15_we0 : OUT STD_LOGIC;
    IMG_V_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_16_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_16_ce0 : OUT STD_LOGIC;
    IMG_V_16_we0 : OUT STD_LOGIC;
    IMG_V_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_17_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_17_ce0 : OUT STD_LOGIC;
    IMG_V_17_we0 : OUT STD_LOGIC;
    IMG_V_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_18_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_18_ce0 : OUT STD_LOGIC;
    IMG_V_18_we0 : OUT STD_LOGIC;
    IMG_V_18_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_19_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_19_ce0 : OUT STD_LOGIC;
    IMG_V_19_we0 : OUT STD_LOGIC;
    IMG_V_19_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_20_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_20_ce0 : OUT STD_LOGIC;
    IMG_V_20_we0 : OUT STD_LOGIC;
    IMG_V_20_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_21_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_21_ce0 : OUT STD_LOGIC;
    IMG_V_21_we0 : OUT STD_LOGIC;
    IMG_V_21_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_22_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_22_ce0 : OUT STD_LOGIC;
    IMG_V_22_we0 : OUT STD_LOGIC;
    IMG_V_22_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_23_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_23_ce0 : OUT STD_LOGIC;
    IMG_V_23_we0 : OUT STD_LOGIC;
    IMG_V_23_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_24_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_24_ce0 : OUT STD_LOGIC;
    IMG_V_24_we0 : OUT STD_LOGIC;
    IMG_V_24_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_25_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_25_ce0 : OUT STD_LOGIC;
    IMG_V_25_we0 : OUT STD_LOGIC;
    IMG_V_25_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    IMG_V_26_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    IMG_V_26_ce0 : OUT STD_LOGIC;
    IMG_V_26_we0 : OUT STD_LOGIC;
    IMG_V_26_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of fast_accel_fast_accel_Pipeline_VITIS_LOOP_14_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv15_1B : STD_LOGIC_VECTOR (14 downto 0) := "000000000011011";
    constant ap_const_lv30_97B5 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000001001011110110101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1072_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln16_fu_582_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln16_reg_700 : STD_LOGIC_VECTOR (4 downto 0);
    signal gmem_addr_read_reg_704 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln16_fu_633_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem_fu_164 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln14_fu_601_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul_fu_168 : STD_LOGIC_VECTOR (29 downto 0);
    signal add_ln16_fu_617_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal i_V_fu_172 : STD_LOGIC_VECTOR (14 downto 0);
    signal i_V_4_fu_568_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_i_V_3 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln14_fu_589_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln14_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_623_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fast_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component fast_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_V_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1072_fu_562_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_V_fu_172 <= i_V_4_fu_568_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_V_fu_172 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    phi_mul_fu_168 <= ap_const_lv30_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    phi_mul_fu_168 <= add_ln16_fu_617_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_164 <= ap_const_lv15_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    phi_urem_fu_164 <= select_ln14_fu_601_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                gmem_addr_read_reg_704 <= m_axi_gmem_RDATA;
                trunc_ln16_reg_700 <= trunc_ln16_fu_582_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    IMG_V_0_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_0_ce0 <= ap_const_logic_1;
        else 
            IMG_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_0_d0 <= gmem_addr_read_reg_704;

    IMG_V_0_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_0_we0 <= ap_const_logic_1;
        else 
            IMG_V_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_10_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_10_ce0 <= ap_const_logic_1;
        else 
            IMG_V_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_10_d0 <= gmem_addr_read_reg_704;

    IMG_V_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_10_we0 <= ap_const_logic_1;
        else 
            IMG_V_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_11_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_11_ce0 <= ap_const_logic_1;
        else 
            IMG_V_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_11_d0 <= gmem_addr_read_reg_704;

    IMG_V_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_11_we0 <= ap_const_logic_1;
        else 
            IMG_V_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_12_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_12_ce0 <= ap_const_logic_1;
        else 
            IMG_V_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_12_d0 <= gmem_addr_read_reg_704;

    IMG_V_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_12_we0 <= ap_const_logic_1;
        else 
            IMG_V_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_13_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_13_ce0 <= ap_const_logic_1;
        else 
            IMG_V_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_13_d0 <= gmem_addr_read_reg_704;

    IMG_V_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_13_we0 <= ap_const_logic_1;
        else 
            IMG_V_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_14_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_14_ce0 <= ap_const_logic_1;
        else 
            IMG_V_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_14_d0 <= gmem_addr_read_reg_704;

    IMG_V_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_14_we0 <= ap_const_logic_1;
        else 
            IMG_V_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_15_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_15_ce0 <= ap_const_logic_1;
        else 
            IMG_V_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_15_d0 <= gmem_addr_read_reg_704;

    IMG_V_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_15_we0 <= ap_const_logic_1;
        else 
            IMG_V_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_16_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_16_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_16_ce0 <= ap_const_logic_1;
        else 
            IMG_V_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_16_d0 <= gmem_addr_read_reg_704;

    IMG_V_16_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_16_we0 <= ap_const_logic_1;
        else 
            IMG_V_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_17_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_17_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_17_ce0 <= ap_const_logic_1;
        else 
            IMG_V_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_17_d0 <= gmem_addr_read_reg_704;

    IMG_V_17_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_11) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_17_we0 <= ap_const_logic_1;
        else 
            IMG_V_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_18_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_18_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_18_ce0 <= ap_const_logic_1;
        else 
            IMG_V_18_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_18_d0 <= gmem_addr_read_reg_704;

    IMG_V_18_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_18_we0 <= ap_const_logic_1;
        else 
            IMG_V_18_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_19_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_19_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_19_ce0 <= ap_const_logic_1;
        else 
            IMG_V_19_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_19_d0 <= gmem_addr_read_reg_704;

    IMG_V_19_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_13) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_19_we0 <= ap_const_logic_1;
        else 
            IMG_V_19_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_1_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_1_ce0 <= ap_const_logic_1;
        else 
            IMG_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_1_d0 <= gmem_addr_read_reg_704;

    IMG_V_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_1_we0 <= ap_const_logic_1;
        else 
            IMG_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_20_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_20_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_20_ce0 <= ap_const_logic_1;
        else 
            IMG_V_20_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_20_d0 <= gmem_addr_read_reg_704;

    IMG_V_20_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_20_we0 <= ap_const_logic_1;
        else 
            IMG_V_20_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_21_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_21_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_21_ce0 <= ap_const_logic_1;
        else 
            IMG_V_21_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_21_d0 <= gmem_addr_read_reg_704;

    IMG_V_21_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_15) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_21_we0 <= ap_const_logic_1;
        else 
            IMG_V_21_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_22_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_22_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_22_ce0 <= ap_const_logic_1;
        else 
            IMG_V_22_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_22_d0 <= gmem_addr_read_reg_704;

    IMG_V_22_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_22_we0 <= ap_const_logic_1;
        else 
            IMG_V_22_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_23_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_23_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_23_ce0 <= ap_const_logic_1;
        else 
            IMG_V_23_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_23_d0 <= gmem_addr_read_reg_704;

    IMG_V_23_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_17) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_23_we0 <= ap_const_logic_1;
        else 
            IMG_V_23_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_24_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_24_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_24_ce0 <= ap_const_logic_1;
        else 
            IMG_V_24_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_24_d0 <= gmem_addr_read_reg_704;

    IMG_V_24_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_24_we0 <= ap_const_logic_1;
        else 
            IMG_V_24_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_25_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_25_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_25_ce0 <= ap_const_logic_1;
        else 
            IMG_V_25_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_25_d0 <= gmem_addr_read_reg_704;

    IMG_V_25_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_19) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_25_we0 <= ap_const_logic_1;
        else 
            IMG_V_25_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_26_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_26_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_26_ce0 <= ap_const_logic_1;
        else 
            IMG_V_26_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_26_d0 <= gmem_addr_read_reg_704;

    IMG_V_26_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((trunc_ln16_reg_700 = ap_const_lv5_1A) or ((trunc_ln16_reg_700 = ap_const_lv5_1B) or ((trunc_ln16_reg_700 = ap_const_lv5_1C) or ((trunc_ln16_reg_700 = ap_const_lv5_1D) or ((trunc_ln16_reg_700 = ap_const_lv5_1E) or (trunc_ln16_reg_700 = ap_const_lv5_1F)))))))) then 
            IMG_V_26_we0 <= ap_const_logic_1;
        else 
            IMG_V_26_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_2_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_2_ce0 <= ap_const_logic_1;
        else 
            IMG_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_2_d0 <= gmem_addr_read_reg_704;

    IMG_V_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_2_we0 <= ap_const_logic_1;
        else 
            IMG_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_3_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_3_ce0 <= ap_const_logic_1;
        else 
            IMG_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_3_d0 <= gmem_addr_read_reg_704;

    IMG_V_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_3_we0 <= ap_const_logic_1;
        else 
            IMG_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_4_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_4_ce0 <= ap_const_logic_1;
        else 
            IMG_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_4_d0 <= gmem_addr_read_reg_704;

    IMG_V_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_4_we0 <= ap_const_logic_1;
        else 
            IMG_V_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_5_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_5_ce0 <= ap_const_logic_1;
        else 
            IMG_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_5_d0 <= gmem_addr_read_reg_704;

    IMG_V_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_5_we0 <= ap_const_logic_1;
        else 
            IMG_V_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_6_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_6_ce0 <= ap_const_logic_1;
        else 
            IMG_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_6_d0 <= gmem_addr_read_reg_704;

    IMG_V_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_6_we0 <= ap_const_logic_1;
        else 
            IMG_V_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_7_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_7_ce0 <= ap_const_logic_1;
        else 
            IMG_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_7_d0 <= gmem_addr_read_reg_704;

    IMG_V_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_7_we0 <= ap_const_logic_1;
        else 
            IMG_V_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_8_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_8_ce0 <= ap_const_logic_1;
        else 
            IMG_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_8_d0 <= gmem_addr_read_reg_704;

    IMG_V_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_8_we0 <= ap_const_logic_1;
        else 
            IMG_V_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_9_address0 <= zext_ln16_fu_633_p1(10 - 1 downto 0);

    IMG_V_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_9_ce0 <= ap_const_logic_1;
        else 
            IMG_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    IMG_V_9_d0 <= gmem_addr_read_reg_704;

    IMG_V_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln16_reg_700)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln16_reg_700 = ap_const_lv5_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            IMG_V_9_we0 <= ap_const_logic_1;
        else 
            IMG_V_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln14_fu_589_p2 <= std_logic_vector(unsigned(phi_urem_fu_164) + unsigned(ap_const_lv15_1));
    add_ln16_fu_617_p2 <= std_logic_vector(unsigned(phi_mul_fu_168) + unsigned(ap_const_lv30_97B5));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (m_axi_gmem_RVALID = ap_const_logic_0);
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1072_fu_562_p2)
    begin
        if (((icmp_ln1072_fu_562_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_V_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_V_fu_172)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_V_3 <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_i_V_3 <= i_V_fu_172;
        end if; 
    end process;


    gmem_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem_blk_n_R <= m_axi_gmem_RVALID;
        else 
            gmem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    i_V_4_fu_568_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_V_3) + unsigned(ap_const_lv15_1));
    icmp_ln1072_fu_562_p2 <= "1" when (ap_sig_allocacmp_i_V_3 = ap_const_lv15_4000) else "0";
    icmp_ln14_fu_595_p2 <= "1" when (unsigned(add_ln14_fu_589_p2) < unsigned(ap_const_lv15_1B)) else "0";
    m_axi_gmem_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_ARID <= ap_const_lv1_0;
    m_axi_gmem_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_ARVALID <= ap_const_logic_0;
    m_axi_gmem_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_AWID <= ap_const_lv1_0;
    m_axi_gmem_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_AWVALID <= ap_const_logic_0;
    m_axi_gmem_BREADY <= ap_const_logic_0;

    m_axi_gmem_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_WDATA <= ap_const_lv8_0;
    m_axi_gmem_WID <= ap_const_lv1_0;
    m_axi_gmem_WLAST <= ap_const_logic_0;
    m_axi_gmem_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_WUSER <= ap_const_lv1_0;
    m_axi_gmem_WVALID <= ap_const_logic_0;
    select_ln14_fu_601_p3 <= 
        add_ln14_fu_589_p2 when (icmp_ln14_fu_595_p2(0) = '1') else 
        ap_const_lv15_0;
    tmp_fu_623_p4 <= phi_mul_fu_168(29 downto 20);
    trunc_ln16_fu_582_p1 <= phi_urem_fu_164(5 - 1 downto 0);
    zext_ln16_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_623_p4),64));
end behav;
